### ISSUE TITLE
Defect-1: Production app getting a lot of console errors

### ISSUE THREAD

**Issue by kkyusufk** [tussharrane/E-Learning-portal#33]
![image](https://user-images.githubusercontent.com/22116082/145066070-a0615a7f-d453-440a-89dc-4c919eeb3815.png)

Acceptance Criteria
- Make sure there are no console errors in prod builf
- Do not spend a ton of time on this, if its not an easy fix please inform me on how to proceed further

**Comment by tussharrane** [comment]
@kkyusufk I could not see the above errors in my browser. Though I saw couple of warnings
![prod_build_warnings](https://user-images.githubusercontent.com/66003209/145152034-501fc802-5e22-447a-b1b4-718b5f446117.png)
.


And then in Netlify deploy settings, I disabled the netlify-drawer tool, and all the warnings were removed. 
So, now I get no warnings and errors in my browser.

**Comment by kkyusufk** [comment]
I do not see errors, so closing this issue. Nice work!
